# 19	Make use of the assert statement to catch AssertionError.
x = 10
y = 20

assert x < y, "AssertionError: x should be less than y"
print("Assertion passed!")
